In [1]:
import pandas as pd
import numpy as np

In [2]:
field = 'Liabilities'

In [3]:
# df2009=pd.read_csv('josh_data'+ '_notes_' + '2009' + field + 'grab_all.csv')
# df2010=pd.read_csv('josh_data'+ '_notes_' + '2010' + field + 'grab_all.csv')
# df2011=pd.read_csv('josh_data'+ '_notes_' + '2011' + field + 'grab_all.csv')
# df2012=pd.read_csv('josh_data'+ '_notes_' + '2012' + field + 'grab_all.csv')
# df2013=pd.read_csv('josh_data'+ '_notes_' + '2013' + field + 'grab_all.csv')
# df2014=pd.read_csv('josh_data'+ '_notes_' + '2014' + field + 'grab_all.csv')
# df2015=pd.read_csv('josh_data'+ '_notes_' + '2015' + field + 'grab_all.csv')
# df2016=pd.read_csv('josh_data'+ '_notes_' + '2016' + field + 'grab_all.csv')
# df2017=pd.read_csv('josh_data'+ '_notes_' + '2017' + field + 'grab_all.csv')
# df2018=pd.read_csv('josh_data'+ '_notes_' + '2018' + field + 'grab_all.csv')

In [4]:
df2009=pd.read_csv('esteban_data'+ '_notes_' + '2009' + field + '.csv')
df2010=pd.read_csv('esteban_data'+ '_notes_' + '2010' + field + '.csv')
df2011=pd.read_csv('esteban_data'+ '_notes_' + '2011' + field + '.csv')
df2012=pd.read_csv('esteban_data'+ '_notes_' + '2012' + field + '.csv')
df2013=pd.read_csv('esteban_data'+ '_notes_' + '2013' + field + '.csv')
df2014=pd.read_csv('esteban_data'+ '_notes_' + '2014' + field + '.csv')
df2015=pd.read_csv('esteban_data'+ '_notes_' + '2015' + field + '.csv')
df2016=pd.read_csv('esteban_data'+ '_notes_' + '2016' + field + '.csv')
df2017=pd.read_csv('esteban_data'+ '_notes_' + '2017' + field + '.csv')
df2018=pd.read_csv('esteban_data'+ '_notes_' + '2018' + field + '.csv')

In [5]:
# df2009=pd.read_csv('esteban_data'+ '2009' + field + '.csv')
# df2010=pd.read_csv('esteban_data'+ '2010' + field + '.csv')
# df2011=pd.read_csv('esteban_data'+ '2011' + field + '.csv')
# df2012=pd.read_csv('esteban_data'+ '2012' + field + '.csv')
# df2013=pd.read_csv('esteban_data'+ '2013' + field + '.csv')
# df2014=pd.read_csv('esteban_data'+ '2014' + field + '.csv')
# df2015=pd.read_csv('esteban_data'+ '2015' + field + '.csv')
# df2016=pd.read_csv('esteban_data'+ '2016' + field + '.csv')
# df2017=pd.read_csv('esteban_data'+ '2017' + field + '.csv')
# df2018=pd.read_csv('esteban_data'+ '2018' + field + '.csv')

In [6]:
# Dropping unnecessary column
for data in [df2009, df2010, df2011, df2012, df2013,df2016, df2017,df2018]:
    del data['Unnamed: 0']

In [7]:
# Compiling Non-U.S Income Data for all years
df = df2009.append(df2010).append(df2011).append(df2012).append(df2013).append(df2014).append(df2015).\
append(df2016).append(df2017).append(df2018)

In [8]:
df.sort_values(['cik','coreg','fy'],inplace=True)

In [9]:
len(df)

55285

In [10]:
del df['Unnamed: 0']

In [11]:
df

,Liabilities,adsh_10k,adsh_other,cik,coreg,ddate,ein,fy,period,qtrs,sic
387,5.694000e+09,0001047469-10-001018,0001104659-10-042282,1800,NaN,20091231.0,NaN,2009.0,20091231,NaN,NaN
388,5.694000e+09,0001047469-10-001018,0001104659-10-042282,1800,NaN,20091231.0,NaN,2009.0,20091231,NaN,NaN
389,5.694000e+09,0001047469-10-001018,0001104659-10-056473,1800,NaN,20091231.0,NaN,2009.0,20091231,NaN,NaN
390,5.694000e+09,0001047469-10-001018,0001104659-10-056473,1800,NaN,20091231.0,NaN,2009.0,20091231,NaN,NaN
588,3.650000e+08,0001047469-11-001056,NaN,1800,NaN,20101231.0,360698440.0,2010.0,20101231,0.0,2834.0
589,7.610000e+09,0001047469-11-001056,NaN,1800,NaN,20101231.0,360698440.0,2010.0,20101231,0.0,2834.0
590,7.975000e+09,0001047469-11-001056,NaN,1800,NaN,20101231.0,360698440.0,2010.0,20101231,0.0,2834.0
8036,3.525121e+06,0001264931-13-000223,0001264931-13-000685,1961,NaN,20121231.0,NaN,2012.0,20121231,NaN,NaN
3054,1.312770e+08,0001188112-12-002832,NaN,2034,NaN,20120630.0,111720520.0,2012.0,20120630,0.0,5160.0
3756,1.287900e+08,0001188112-13-002611,NaN,2034,NaN,20130630.0,111720520.0,2013.0,20130630,0.0,5160.0
7519,2.344000e+08,0001571049-14-004448,NaN,2034,NaN,20140630.0,111720520.0,2014.0,20140630,0.0,5160.0
7077,2.355630e+08,0001571049-15-007509,NaN,2034,NaN,20150630.0,111720520.0,2015.0,20150630,0.0,5122.0
6516,2.363360e+08,0001571049-16-017785,NaN,2034,NaN,20160630.0,111720520.0,2016.0,20160630,0.0,5122.0
2421,6.331180e+08,0001144204-17-045100,NaN,2034,NaN,20170630.0,111720520.0,2017.0,20170630,0.0,5122.0
1100,2.744681e+07,0001026608-12-000017,NaN,2098,NaN,20111231.0,60236700.0,2011.0,20111231,0.0,3420.0
1433,3.696151e+07,0001026608-13-000014,NaN,2098,NaN,20121231.0,60236700.0,2012.0,20121231,0.0,3420.0
1599,3.307373e+07,0001026608-14-000011,NaN,2098,NaN,20131231.0,60236700.0,2013.0,20131231,0.0,3420.0
1545,3.988003e+07,0001026608-15-000007,NaN,2098,NaN,20141231.0,60236700.0,2014.0,20141231,0.0,3420.0
1472,3.823780e+07,0001026608-16-000091,NaN,2098,NaN,20151231.0,60236700.0,2015.0,20151231,0.0,3420.0
1401,4.594575e+07,0001026608-17-000009,NaN,2098,NaN,20161231.0,60236700.0,2016.0,20161231,0.0,3420.0
1088,6.479181e+07,0001026608-18-000010,NaN,2098,NaN,20171231.0,60236700.0,2017.0,20171231,0.0,3420.0
48,2.681580e+08,0000002178-12-000010,NaN,2178,NaN,20111231.0,741753147.0,2011.0,20111231,0.0,5172.0
36,2.836430e+08,0000002178-13-000014,NaN,2178,NaN,20121231.0,741753147.0,2012.0,20121231,0.0,5172.0
62,2.933970e+08,0000002178-14-000010,NaN,2178,NaN,20131231.0,741753147.0,2013.0,20131231,0.0,5172.0
42,1.833170e+08,0000002178-15-000014,NaN,2178,NaN,20141231.0,741753147.0,2014.0,20141231,0.0,5172.0
40,9.070500e+07,0000002178-16-000064,NaN,2178,NaN,20151231.0,741753147.0,2015.0,20151231,0.0,5172.0
43,9.556000e+07,0000002178-17-000019,NaN,2178,NaN,20161231.0,741753147.0,2016.0,20161231,0.0,5172.0
32,1.355850e+08,0000002178-18-000009,NaN,2178,NaN,20171231.0,741753147.0,2017.0,20171231,0.0,5172.0
5517,3.778000e+06,0001354488-12-001013,NaN,2186,NaN,20111231.0,593486297.0,2011.0,20111231,0.0,3663.0
6158,3.776000e+06,0001354488-13-000998,NaN,2186,NaN,20121231.0,593486297.0,2012.0,20121231,0.0,3663.0
...,...,...,...,...,...,...,...,...,...,...,...
5,2.450653e+07,0001144204-18-008162,NaN,1706946,NaN,20171231.0,0.0,2017.0,20171231,0.0,6770.0
4818,3.561000e+09,0001707092-18-000008,NaN,1707092,NaN,20171231.0,981367514.0,2017.0,20171231,0.0,3714.0
15,1.227151e+07,0001213900-18-003754,NaN,1707306,NaN,20171231.0,821329677.0,2017.0,20171231,0.0,6770.0
4819,0.000000e+00,0001708035-18-000005,NaN,1708035,NaN,20171231.0,813406833.0,2017.0,20171231,0.0,2800.0
4820,2.783536e+09,0001708035-18-000005,NaN,1708035,NaN,20171231.0,813406833.0,2017.0,20171231,0.0,2800.0
4589,2.954620e+08,0001628280-18-002933,NaN,1708055,NaN,20171231.0,821669692.0,2017.0,20171231,0.0,7373.0
4821,2.480300e+07,0001708301-18-000014,NaN,1708301,NaN,20171231.0,821646447.0,2017.0,20171231,0.0,4610.0
29,1.340530e+05,0001683168-18-000741,NaN,1708341,NaN,20171231.0,821659427.0,2017.0,20171231,0.0,6770.0
30,1.055000e+06,0001708405-18-000019,NaN,1708405,NaN,20171231.0,821719041.0,2017.0,20171231,0.0,6798.0
1758,1.969920e+08,0001144204-18-018015,NaN,1709017,NaN,20171231.0,0.0,2017.0,20171231,0.0,6035.0
4822,2.798250e+08,0001709164-18-000011,NaN,1709164,NaN,20171231.0,311236686.0,2017.0,20171231,0.0,3634.0
14,1.426397e+07,0001213900-18-003531,NaN,1709682,NaN,20171231.0,0.0,2017.0,20171231,0.0,6770.0
13,1.209489e+07,0001213900-18-003466,NaN,1709768,NaN,20171231.0,981370747.0,2017.0,20171231,0.0,6770.0
4823,2.363458e+09,0001710366-18-000006,NaN,1710366,NaN,20171231.0,0.0,2017.0,20171231,0.0,1220.0
3996,6.400000e+05,0001564590-18-005252,NaN,1711279,NaN,20171231.0,810930882.0,2017.0,20171231,0.0,2836.0
4824,1.879000e+06,0001711485-18-000007,NaN,1711485,NaN,20171231.0,822089921.0,2017.0,20171231,0.0,1311.0
4825,1.513100e+06,0001711631-18-000007,NaN,1711631,NaN,20171231.0,822097510.0,2017.0,20171231,0.0,1311.0
4826,2.802100e+06,0001711736-18-000007,NaN,1711736,NaN,20171231.0,822114425.0,2017.0,20171231,0.0,1311.0
4827,1.056000e+08,0001712184-18-000080,NaN,1712184,NaN,20171231.0,0.0,2017.0,20171231,0.0,4841.0
4828,8.926300e+09,0001712184-18-000080,NaN,1712184,NaN,20171231.0,0.0,2017.0,20171231,0.0,4841.0
2991,5.017500e+04,0001477932-18-001402,NaN,1713809,NaN,20171231.0,371863750.0,2017.0,20171231,0.0,7374.0
11,1.221679e+07,0001193125-18-099755,NaN,1713952,NaN,20171231.0,0.0,2017.0,20171231,0.0,6770.0
5135,1.373415e+09,0001715629-18-000002,NaN,1715629,FelCorLodgingLP,20171231.0,0.0,2017.0,20171231,0.0,6798.0
5136,1.373415e+09,0001715629-18-000002,NaN,1715629,RangersSubILLC,20171231.0,0.0,2017.0,20171231,0.0,6798.0
5137,-3.270900e+07,0001715629-18-000002,NaN,1715629,NaN,20171231.0,0.0,2017.0,20171231,0.0,6798.0
5138,1.360500e+07,0001715629-18-000002,NaN,1715629,NaN,20171231.0,0.0,2017.0,20171231,0.0,6798.0
5139,2.974990e+08,0001715629-18-000002,NaN,1715629,NaN,20171231.0,0.0,2017.0,20171231,0.0,6798.0
5140,1.095020e+09,0001715629-18-000002,NaN,1715629,NaN,20171231.0,0.0,2017.0,20171231,0.0,6798.0
27,7.156239e+06,0001615774-18-001769,NaN,1716947,NaN,20171231.0,822755287.0,2017.0,20171231,0.0,6770.0
31,0.000000e+00,0001723128-18-000005,NaN,1723128,NaN,20171231.0,0.0,2017.0,20171231,0.0,2834.0

In [12]:
df.coreg = df.coreg.fillna('null')

In [13]:
df = df.drop_duplicates(['cik','coreg','period',field])

In [14]:
len(df)

52690

In [15]:
# df.to_csv('liabilities_with_notes.csv')